src/Entity/ForecastReminder.php
<?php

/*
 * This file is part of JoliCode's Forecast Tools project.
 *
 * (c) JoliCode <coucou@jolicode.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace App\Entity;

use App\Validator\Constraints as AppAssert;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;

#[ORM\Entity(repositoryClass: \App\Repository\ForecastReminderRepository::class)]
class ForecastReminder implements \Stringable
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private ?int $id = null;

    /**
     * @AppAssert\CronExpression(message="The value ""{{ value }}"" is not a valid cron expression.")
     */
    #[ORM\Column(type: 'string', length: 255)]
    private string $cronExpression = '0 18 * * *';

    #[ORM\ManyToOne(targetEntity: User::class, inversedBy: 'forecastReminders')]
    #[ORM\JoinColumn(nullable: true, onDelete: 'SET NULL')]
    private ?User $updatedBy = null;

    /**
     * @Gedmo\Timestampable(on="update")
     */
    #[ORM\Column(type: 'datetime')]
    private ?\DateTimeInterface $updatedAt = null;

    #[ORM\Column(type: 'datetime', nullable: true)]
    private ?\DateTimeInterface $lastTimeSentAt = null;

    #[ORM\Column(type: 'string', length: 255)]
    private string $defaultActivityName = 'no activity defined';

    #[ORM\Column(type: 'string', length: 255)]
    private string $timeOffActivityName = 'holidays (until %s)';

    /**
     * @var Collection<int, ProjectOverride>
     */
    #[ORM\OneToMany(targetEntity: ProjectOverride::class, mappedBy: 'forecastReminder', orphanRemoval: true, cascade: ['persist'])]
    private Collection $projectOverrides;

    /**
     * @var Collection<int, ClientOverride>
     */
    #[ORM\OneToMany(targetEntity: ClientOverride::class, mappedBy: 'forecastReminder', orphanRemoval: true, cascade: ['persist'])]
    private Collection $clientOverrides;

    /**
     * @var array<array-key, int>
     */
    #[ORM\Column(type: 'array', nullable: true)]
    private ?array $timeOffProjects = [];

    /**
     * @var array<array-key, int>
     */
    #[ORM\Column(type: 'array', nullable: true)]
    private ?array $onlyUsers = [];

    /**
     * @var array<array-key, int>
     */
    #[ORM\Column(type: 'array', nullable: true)]
    private ?array $exceptUsers = [];

    #[ORM\OneToOne(targetEntity: ForecastAccount::class, inversedBy: 'forecastReminder', cascade: ['persist', 'remove'])]
    #[ORM\JoinColumn(nullable: false, onDelete: 'CASCADE')]
    private ForecastAccount $forecastAccount;

    public function __construct()
    {
        $this->projectOverrides = new ArrayCollection();
        $this->clientOverrides = new ArrayCollection();
    }

    public function __toString(): string
    {
        return sprintf('Reminder for "%s"', $this->forecastAccount->getName());
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCronExpression(): ?string
    {
        return $this->cronExpression;
    }

    public function setCronExpression(string $cronExpression): self
    {
        $this->cronExpression = $cronExpression;

        return $this;
    }

    public function getUpdatedBy(): ?User
    {
        return $this->updatedBy;
    }

    public function setUpdatedBy(?User $updatedBy): self
    {
        $this->updatedBy = $updatedBy;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(\DateTimeInterface $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    public function getLastTimeSentAt(): ?\DateTimeInterface
    {
        return $this->lastTimeSentAt;
    }

    public function setLastTimeSentAt(\DateTimeInterface $lastTimeSentAt): self
    {
        $this->lastTimeSentAt = $lastTimeSentAt;

        return $this;
    }

    public function getDefaultActivityName(): ?string
    {
        return $this->defaultActivityName;
    }

    public function setDefaultActivityName(string $defaultActivityName): self
    {
        $this->defaultActivityName = $defaultActivityName;

        return $this;
    }

    public function getTimeOffActivityName(): ?string
    {
        return $this->timeOffActivityName;
    }

    public function setTimeOffActivityName(string $timeOffActivityName): self
    {
        $this->timeOffActivityName = $timeOffActivityName;

        return $this;
    }

    /**
     * @return Collection<int, ProjectOverride>|ProjectOverride[]
     */
    public function getProjectOverrides(): Collection
    {
        return $this->projectOverrides;
    }

    public function addProjectOverride(ProjectOverride $projectOverride): self
    {
        if (!$this->projectOverrides->contains($projectOverride)) {
            $this->projectOverrides[] = $projectOverride;
            $projectOverride->setForecastReminder($this);
        }

        return $this;
    }

    public function removeProjectOverride(ProjectOverride $projectOverride): self
    {
        if ($this->projectOverrides->contains($projectOverride)) {
            $this->projectOverrides->removeElement($projectOverride);
        }

        return $this;
    }

    /**
     * @return Collection<int, ClientOverride>|ClientOverride[]
     */
    public function getClientOverrides(): Collection
    {
        return $this->clientOverrides;
    }

    public function addClientOverride(ClientOverride $clientOverride): self
    {
        if (!$this->clientOverrides->contains($clientOverride)) {
            $this->clientOverrides[] = $clientOverride;
            $clientOverride->setForecastReminder($this);
        }

        return $this;
    }

    public function removeClientOverride(ClientOverride $clientOverride): self
    {
        if ($this->clientOverrides->contains($clientOverride)) {
            $this->clientOverrides->removeElement($clientOverride);
        }

        return $this;
    }

    /**
     * @return array<array-key, int>
     */
    public function getTimeOffProjects(): ?array
    {
        return $this->timeOffProjects;
    }

    /**
     * @param array<array-key, int> $timeOffProjects
     */
    public function setTimeOffProjects(?array $timeOffProjects): self
    {
        $this->timeOffProjects = $timeOffProjects;

        return $this;
    }

    /**
     * @return array<array-key, int>
     */
    public function getOnlyUsers(): ?array
    {
        return $this->onlyUsers;
    }

    /**
     * @param array<array-key, int> $onlyUsers
     */
    public function setOnlyUsers(?array $onlyUsers): self
    {
        $this->onlyUsers = $onlyUsers;

        return $this;
    }

    /**
     * @return array<array-key, int>
     */
    public function getExceptUsers(): ?array
    {
        return $this->exceptUsers;
    }

    /**
     * @param array<array-key, int> $exceptUsers
     */
    public function setExceptUsers(?array $exceptUsers): self
    {
        $this->exceptUsers = $exceptUsers;

        return $this;
    }

    public function getForecastAccount(): ?ForecastAccount
    {
        return $this->forecastAccount;
    }

    public function setForecastAccount(ForecastAccount $forecastAccount): self
    {
        $this->forecastAccount = $forecastAccount;

        return $this;
    }

    public function getIsMuted(): ?bool
    {
        $forecastAccountSlackTeams = $this->getForecastAccount()->getForecastAccountSlackTeams();

        foreach ($forecastAccountSlackTeams as $forecastAccountSlackTeam) {
            if (null !== $forecastAccountSlackTeam->getChannelId()) {
                return false;
            }
        }

        return true;
    }
}

src/Controller/Organization/CleanupController.php
<?php

/*
 * This file is part of JoliCode's Forecast Tools project.
 *
 * (c) JoliCode <coucou@jolicode.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace App\Controller\Organization;

use App\Client\HarvestClient;
use App\Entity\ForecastAccount;
use App\Form\CleanupType;
use JoliCode\Harvest\Api\Model\ClientsClientIdPatchBody;
use JoliCode\Harvest\Api\Model\ProjectsProjectIdPatchBody;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;

#[Route(path: '/{slug}/cleanup', name: 'organization_cleanup_', defaults: ['menu' => 'cleanup'])]
#[IsGranted('admin', subject: 'forecastAccount')]
#[IsGranted('harvest_admin', subject: 'forecastAccount')]
class CleanupController extends AbstractController
{
    public function __construct(
        private readonly HarvestClient $harvestClient,
    ) {
    }

    #[Route(path: '/', name: 'index')]
    public function index(Request $request, ForecastAccount $forecastAccount): \Symfony\Component\HttpFoundation\Response
    {
        $form = $this->createForm(CleanupType::class, null, ['harvestAccount' => $forecastAccount->getHarvestAccount()]);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $data = $form->getData();

            foreach ($data['project'] as $projectId) {
                // disabling a project on Harvest will also disable it on Forecast
                $patch = new ProjectsProjectIdPatchBody();
                $patch->setIsActive(false);
                $this->harvestClient->__client()->updateProject($projectId, $patch);
            }

            foreach ($data['client'] as $clientId) {
                // disabling a project on Harvest will also disable it on Forecast
                $patch = new ClientsClientIdPatchBody();
                $patch->setIsActive(false);
                $this->harvestClient->__client()->updateClient($clientId, $patch);
            }

            $this->addFlash(
                'success',
                '👋 The items have been archived!'
            );

            return $this->redirectToRoute('organization_cleanup_index', ['slug' => $forecastAccount->getSlug()]);
        }

        return $this->render('organization/cleanup/index.html.twig', [
            'forecastAccount' => $forecastAccount,
            'form' => $form,
            'controller_name' => 'CleanupController',
        ]);
    }
}

src/Controller/Organization/MassInsertionController.php
<?php

/*
 * This file is part of JoliCode's Forecast Tools project.
 *
 * (c) JoliCode <coucou@jolicode.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace App\Controller\Organization;

use App\Client\ForecastClient;
use App\Client\HarvestClient;
use App\DataSelector\ForecastDataSelector;
use App\DataSelector\HarvestDataSelector;
use App\Entity\ForecastAccount;
use App\Form\MassInsertType;
use JoliCode\Forecast\Api\Model\Assignment;
use JoliCode\Forecast\Api\Model\AssignmentsPostBody;
use JoliCode\Harvest\Api\Model\TimeEntriesPostBody;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;

#[Route(path: '/{slug}/mass-insertion', name: 'organization_mass_insertion_', defaults: ['menu' => 'mass-insertion'])]
#[IsGranted('admin', subject: 'forecastAccount')]
#[IsGranted('harvest_admin', subject: 'forecastAccount')]
class MassInsertionController extends AbstractController
{
    public function __construct(private readonly ForecastClient $forecastClient, private readonly HarvestClient $harvestClient, private readonly ForecastDataSelector $forecastDataSelector, private readonly HarvestDataSelector $harvestDataSelector)
    {
    }

    #[Route(path: '/', name: 'index')]
    public function index(Request $request, ForecastAccount $forecastAccount): \Symfony\Component\HttpFoundation\Response
    {
        $form = $this->createForm(MassInsertType::class);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $data = $form->getData();

            if (true === $data['harvest']) {
                // search the Harvest project
                $forecastProjects = $this->forecastDataSelector->getProjectsById(null, true);
                $harvestProjectId = $forecastProjects[$data['project']]->getHarvestId();
                $forecastPeople = $this->forecastDataSelector->getPeopleById();

                // search the task
                $harvestTasks = $this->harvestDataSelector->getTaskAssignmentsForProjectId($harvestProjectId);
                $harvestTaskAssignment = array_shift($harvestTasks);
            }

            foreach ($data['people'] as $personId) {
                if (true === $data['forecast']) {
                    $assignment = new Assignment();
                    $assignment->setAllocation($data['duration'] * 3600);
                    $assignment->setEndDate($data['date']);
                    $assignment->setNotes($data['comment']);
                    $assignment->setPersonId($personId);
                    $assignment->setProjectId($data['project']);
                    $assignment->setRepeatedAssignmentSetId(null);
                    $assignment->setStartDate($data['date']);

                    $forecastBody = new AssignmentsPostBody();
                    $forecastBody->setAssignment($assignment);
                    $this->forecastClient->__client()->createAssignment($forecastBody);
                }

                if (true === $data['harvest']) {
                    // search the harvest user
                    $harvestUserId = $forecastPeople[$personId]->getHarvestUserId();

                    // create the harvest timeEntry
                    $harvestBody = new TimeEntriesPostBody();
                    $harvestBody->setHours($data['duration']);
                    $harvestBody->setNotes($data['comment']);
                    $harvestBody->setProjectId($harvestProjectId);
                    $harvestBody->setSpentDate($data['date']);
                    $harvestBody->setTaskId($harvestTaskAssignment->getTask()->getId());
                    $harvestBody->setUserId($harvestUserId);
                    $this->harvestClient->__client()->createTimeEntry($harvestBody);
                }
            }

            $this->addFlash(
                'success',
                '👋 The entries have been added!'
            );

            return $this->redirectToRoute('organization_mass_insertion_index', ['slug' => $forecastAccount->getSlug()]);
        }

        return $this->render('organization/mass_insertion/index.html.twig', [
            'forecastAccount' => $forecastAccount,
            'form' => $form,
            'controller_name' => 'MassInsertionController',
        ]);
    }
}

src/Controller/OrganizationController.php
<?php

/*
 * This file is part of JoliCode's Forecast Tools project.
 *
 * (c) JoliCode <coucou@jolicode.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace App\Controller;

use App\Entity\ForecastAccount;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;

#[Route(path: '/{slug}', name: 'organization_')]
class OrganizationController extends AbstractController
{
    #[Route(path: '/', name: 'homepage')]
    public function homepage(ForecastAccount $forecastAccount): \Symfony\Component\HttpFoundation\Response
    {
        return $this->render('organization/homepage.html.twig', [
            'forecastAccount' => $forecastAccount,
        ]);
    }
}

templates/organization/reminder/index.html.twig
{% extends 'organization/base.html.twig' %}

{% block title %}Reminder | {{ parent() }}{% endblock %}

{% form_theme form _self %}

{% block _forecast_reminder_projectOverrides_entry_row %}
    <div class="d-flex flex-wrap flex-row pb-3">
        <div class="col-md-5 p-0">
            {{ form_label(form.projectId, null, { label_attr: { class: 'd-md-none' }}) }}
            {{ form_errors(form.projectId) }}
            {{ form_widget(form.projectId) }}
            {{ form_help(form.projectId) }}
        </div>
        <div class="col-md-5 p-0 ps-md-3">
            {{ form_label(form.name, null, { label_attr: { class: 'd-md-none' }}) }}
            {{ form_errors(form.name) }}
            {{ form_widget(form.name, { attr: { class: 'form-control' }}) }}
            {{ form_help(form.name) }}
        </div>
    </div>
{% endblock %}

{% block _forecast_reminder_clientOverrides_entry_row %}
    <div class="d-flex flex-wrap flex-row pb-3">
        <div class="col-md-5 p-0">
            {{ form_label(form.clientId, null, { label_attr: { class: 'd-md-none' }}) }}
            {{ form_errors(form.clientId) }}
            {{ form_widget(form.clientId) }}
            {{ form_help(form.clientId) }}
        </div>
        <div class="col-md-5 p-0 ps-md-3">
            {{ form_label(form.name, null, { label_attr: { class: 'd-md-none' }}) }}
            {{ form_errors(form.name) }}
            {{ form_widget(form.name, { attr: { class: 'form-control' }}) }}
            {{ form_help(form.name) }}
        </div>
    </div>
{% endblock %}

{% block content %}
    {% for message in app.flashes('success') %}
        <div class="flash-notice">
            {{ message }}
        </div>
    {% endfor %}

    {% if forecastAccount.forecastAccountSlackTeams|length == 0 %}
        {% set disabled = ' disabled' %}
    {% else %}
        {% set disabled = '' %}
    {% endif %}

    <nav>
        <div class="nav nav-tabs" id="nav-tab" role="tablist">
            <a class="nav-item nav-link active" id="workspaces-tab" data-bs-toggle="tab" href="#nav-workspaces" role="tab" aria-controls="nav-workspaces" aria-selected="true">Schedule</a>
            <a class="nav-item nav-link{{ disabled }}" id="labels-tab" data-bs-toggle="tab" href="#nav-labels" role="tab" aria-controls="nav-labels" aria-selected="false">Labels</a>
            <a class="nav-item nav-link{{ disabled }}" id="users-tab" data-bs-toggle="tab" href="#nav-users" role="tab" aria-controls="nav-users" aria-selected="false">Users</a>
            <a class="nav-item nav-link{{ disabled }}" id="project-overrides-tab" data-bs-toggle="tab" href="#nav-project-overrides" role="tab" aria-controls="nav-project-overrides" aria-selected="false">Project overrides</a>
            <a class="nav-item nav-link{{ disabled }}" id="client-overrides-tab" data-bs-toggle="tab" href="#nav-client-overrides" role="tab" aria-controls="nav-client-overrides" aria-selected="false">Client overrides</a>
        </div>
    </nav>

    <div class="card border-top-0">
        {{ form_start(form) }}
            <div class="tab-content" id="nav-tabContent">
                <div class="tab-pane show active" id="nav-workspaces" role="tabpanel" aria-labelledby="workspaces-tab">
                    <div class="card-body">
                        {{ form_errors(form) }}
                        {{ form_row(form.cronExpression) }}

                        {% if forecastAccount.forecastAccountSlackTeams|length == 0 %}
                            <div class="alert alert-danger mb-0 d-flex" role="alert">
                                <div class="flex-grow-1 py-1">This reminder cannot be executed, as no Slack workspace has been added to your account.</div>
                            </div>
                        {% elseif forecastAccount.forecastReminder is null or forecastAccount.forecastReminder.isMuted %}
                            <div class="alert alert-danger mb-0 d-flex" role="alert">
                                <div class="flex-grow-1 py-1">This reminder does not post in any Slack team. Please choose a Channel for at least one Slack team.</div>
                            </div>
                        {% endif %}

                        <div class="d-flex flex-wrap flex-row">
                            {% if forecastAccount.forecastAccountSlackTeams|length > 0 %}
                                {% for forecastAccountSlackTeamForm in form.forecastAccount.forecastAccountSlackTeams %}
                                    {% set forecastAccountSlackTeam = forecastAccountSlackTeamForm.vars.value %}
                                    <div class="col-md-4 col-xl-3 mt-3 me-3">
                                        <div class="card">
                                            <div class="card-body">
                                                <button type="button" data-href="{{ organization_path('settings_slack_delete', {forecastAccountSlackTeamId: forecastAccountSlackTeam.id})}}" class="btn-close position-absolute" aria-label="Close" style="top: 1rem; right: 1rem"  data-bs-toggle="modal" data-bs-target="#confirm-delete"></button>
                                                <h5 class="card-title">{{ forecastAccountSlackTeam.slackTeam.teamName }}</h5>
                                                <p class="card-text">
                                                    Added by <code>{{ forecastAccountSlackTeam.updatedBy | default('(deleted user)') }}</code><br />
                                                    Added on <code>{{ forecastAccountSlackTeam.updatedAt|date('F jS, Y, G:i')  }}</code><br />
                                                    {% if forecastAccountSlackTeam.channel %}
                                                        Posts in <code>{{ forecastAccountSlackTeam.channel }}</code><br />
                                                    {% endif %}
                                                </p>
                                            </div>
                                            <div class="card-footer">
                                                {{ form_label(forecastAccountSlackTeamForm.channelId) }}
                                                {{ form_errors(forecastAccountSlackTeamForm.channelId) }}
                                                {{ form_widget(forecastAccountSlackTeamForm.channelId, { attr: { class: 'form-control' }}) }}
                                                {{ form_help(forecastAccountSlackTeamForm.channelId) }}
                                            </div>
                                        </div>
                                    </div>
                                {% endfor %}
                            {% endif %}

                            <div class="card card-body col-md-4 col-xl-3 mt-3 me-3">
                                <h5 class="card-title">Add a Slack workspace</h5>
                                {% if is_granted('admin', forecastAccount) %}
                                    <p class="card-text">
                                        <a href="{{ organization_path('settings_slack') }}">Add a Slack workspace</a> to receive the reminder in this workspace.
                                    </p>
                                    <p class="card-text">
                                        If you add several workspaces, the reminder will be sent to all of these workspaces.
                                    </p>
                                    <p>
                                        <a href="{{ organization_path('settings_slack_install') }}"><img alt="Add to Slack" height="40" width="139" src="https://platform.slack-edge.com/img/add_to_slack.png" srcset="https://platform.slack-edge.com/img/add_to_slack.png 1x, https://platform.slack-edge.com/img/add_to_slack@2x.png 2x"></a>
                                    </p>
                                {% else %}
                                    <p class="card-text">
                                        Only your Forecast admins are allowed to setup and configure Slack reminders. To enable Slack reminders for your Forecast Account, ask a Forecast admin to add a Slack workspace to your organization.
                                    </p>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>

                <div class="tab-pane" id="nav-labels" role="tabpanel" aria-labelledby="labels-tab">
                    <div class="card-body">
                        {{ form_row(form.defaultActivityName) }}

                        <div class="mb-3">
                            {{ form_label(form.timeOffProjects) }}
                            {{ form_errors(form.timeOffProjects) }}
                            {{ form_widget(form.timeOffProjects, { attr: { class: 'select2', multiple: 'multiple' }}) }}
                            {{ form_help(form.timeOffProjects) }}
                        </div>

                        {{ form_row(form.timeOffActivityName) }}
                    </div>
                </div>

                <div class="tab-pane" id="nav-users" role="tabpanel" aria-labelledby="users-tab">
                    <div class="card-body">
                        <div class="mb-3">
                            {{ form_label(form.onlyUsers) }}
                            {{ form_errors(form.onlyUsers) }}
                            {{ form_widget(form.onlyUsers, { attr: { class: 'select2', multiple: 'multiple' }}) }}
                            {{ form_help(form.onlyUsers)|raw }}
                        </div>
                        <div class="mb-3">
                            {{ form_label(form.exceptUsers) }}
                            {{ form_errors(form.exceptUsers) }}
                            {{ form_widget(form.exceptUsers, { attr: { class: 'select2', multiple: 'multiple' }}) }}
                            {{ form_help(form.exceptUsers)|raw }}
                        </div>
                    </div>
                </div>

                <div class="tab-pane" id="nav-project-overrides" role="tabpanel" aria-labelledby="project-overrides-tab">
                    <div class="card-body">
                        <div class="mb-3">
                            {{ form_label(form.projectOverrides, null, { label_attr: { class: 'd-md-none' }}) }}
                            {{ form_help(form.projectOverrides, { help_attr: { class: 'text-normal' }}) }}
                            {{ form_errors(form.projectOverrides) }}
                            <div>
                                {{ form_widget(form.projectOverrides, { attr: { class: 'dynamic-form-container' }}) }}
                            </div>
                        </div>
                    </div>
                </div>

                <div class="tab-pane" id="nav-client-overrides" role="tabpanel" aria-labelledby="client-overrides-tab">
                    <div class="card-body">
                        <div class="mb-3">
                            {{ form_label(form.clientOverrides, null, { label_attr: { class: 'd-md-none' }}) }}
                            {{ form_help(form.clientOverrides, { help_attr: { class: 'text-normal' }}) }}
                            {{ form_errors(form.clientOverrides) }}
                            <div>
                                {{ form_widget(form.clientOverrides, { attr: { class: 'dynamic-form-container' }}) }}
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="card-footer text-end">
                {% if forecastAccount.forecastReminder %}
                    <small class="float-start mt-2">
                        last updated by <code>{{ forecastAccount.forecastReminder.updatedBy | default('(deleted user)') }}</code>
                        on <code>{{ forecastAccount.forecastReminder.updatedAt|date('F jS, Y, G:i')  }}</code>
                    </small>
                {% endif %}
                {{ form_widget(form.save) }}
            </div>
        {{ form_end(form) }}
    </div>

    <div class="modal fade" id="confirm-delete" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    Delete this Slack workspace?
                </div>
                <div class="modal-body">
                    Do you really want to delete this Slack workspace? If you confirm, the reminder
                    will not be sent to this workspace anymore.
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-bs-dismiss="modal">Cancel</button>
                    <a class="btn btn-danger btn-ok">Yes, delete</a>
                </div>
            </div>
        </div>
    </div>

    <script>
    document.addEventListener("DOMContentLoaded", function(event) {
        dynamicForm('add a new override');

        jQuery('#confirm-delete').on('show.bs.modal', function(e) {
            jQuery(this).find('.btn-ok').attr('href', jQuery(e.relatedTarget).data('href'));
        });
    });
    </script>
{% endblock %}